version: "3.9"

services:
  library:
    container_name: library
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  pgdata: { }